### ISSUE TITLE
TypeError: Can't convert 'IPv6Address' object to str implicitly

### ISSUE THREAD

**Issue by boutier** [fingon/pybabel#3]
```
Traceback (most recent call last):
  File "babeld.py", line 191, in <module>
    sys.loop()
  File "babeld.py", line 89, in loop
    self.poll()
  File "babeld.py", line 84, in poll
    l[0].run()
  File "babeld.py", line 62, in run
    self.cb(*self.a)
  File "/home/boutier/programmation/networking/pybabel/pybabel/babel.py", line 97, in tlv_send_timer
    self.send_tlvs(self.tlv_q)
  File "/home/boutier/programmation/networking/pybabel/pybabel/babel.py", line 123, in send_tlvs
    self.get_sys().send_unicast(self.i.ifname, self.ip, b)
  File "babeld.py", line 120, in send_unicast
    babel.interface(ifname).s.sendto(b, (a, BABEL_PORT, 0, ifindex))
TypeError: Can't convert 'IPv6Address' object to str implicitly
```

**Comment by fingon** [comment]
Fixed that (+ another buglet) in 0057e434ab243e7f6cf6e0dcec422c0a801c998d - babeld.py not being covered by unit tests hurts but hopefully it is simple enough it will not break often :) Thanks for testing anyway!
